MovieApp/Models/CategoryMovie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class CategoryMovie
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MovieApp/Models/CategorySeries.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class CategorySeries
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MovieApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Stars { get; set; }
        public string Director { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
        public int Status { get; set; }

    }
}

MovieApp/Models/MovieCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<CategoryMovie> Categories { get; set; }
    }
}

MovieApp/Models/SearchModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class SearchModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    }
}

MovieApp/Models/SearchMovieSeriesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class SearchMovieSeriesModel
    {
        public Series AllSeries { get; set; }
        public Movie AllMovies { get; set; }
        public IEnumerable<Series> Series { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
    }
}

MovieApp/Models/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Series
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Stars { get; set; }
        public string Director { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
        public int Status { get; set; }
    }
}

MovieApp/Models/SeriesCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class SeriesCategoryModel
    {
        public Series Serie { get; set; }
        public IEnumerable<Series> Series { get; set; }
        public IEnumerable<CategorySeries> Categories { get; set; }
    }
}

MovieApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JustWatchApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Search(string q)
        {
            var allSeries = SeriesRepository.Series.Where(x => x.Name.ToLower().Contains(q.ToLower())).Select(x => new SearchModel { Id = x.Id, Name = x.Name, Description = x.ShortDescription, ImageUrl = x.ImageUrl, Status = x.Status }).ToList();
            var allMovies = MovieRepository.Movies.Where(x => x.Name.ToLower().Contains(q.ToLower())).Select(x => new SearchModel { Id = x.Id, Name = x.Name, Description = x.ShortDescription, ImageUrl = x.ImageUrl, Status = x.Status }).ToList();
            var list = allSeries.Union(allMovies).ToList();
            if (string.IsNullOrWhiteSpace(q))
                return View("Index");

            return View("List", list);
        }
        public IActionResult List()
        {
            return View();
        }
    }

}

MovieApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JustWatchApplication.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index(int? id, int page = 1, int category = 0)
        {
            //int pageSize = 4;
            var movies = MovieRepository.Movies;
            //movies = MovieRepository.Movies.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            //ViewBag.PageCount = (int)Math.Ceiling(movies.Count() / (double)pageSize);
            //ViewBag.PageSize = pageSize;
            //ViewBag.CurrentPage = page;
            //ViewBag.CurrentCategory = category;

            if (id != null && id != 1)
            {
                //movies = (movies.Where(x => x.CategoryId == id).ToList()).Skip((page - 1) * pageSize).Take(pageSize).ToList();
                movies = movies.Where(x => x.CategoryId == id).ToList();
            }
            else if (id == 1)
            {
                //movies = MovieRepository.Movies.Skip((page - 1) * pageSize).Take(pageSize).ToList();
                movies = MovieRepository.Movies;
            }
            return View(movies);
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            return View(MovieRepository.GetById(id));
        }
        public IActionResult List()
        {
            return View();
        }

    }
}

MovieApp/Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Controllers
{
    public class SeriesController : Controller
    {
        public IActionResult Index(int? id)
        {
            var series = SeriesRepository.Series;
            if (id != null && id != 1)
            {
                series = series.Where(x => x.CategoryId == id).ToList();
            }
            else if (id == 1)
            {
                series = SeriesRepository.Series;
            }
            return View(series);
        }
        public IActionResult Details(int id)
        {
            return View(SeriesRepository.GetById(id));
        }
        public IActionResult Create()
        {
            return View();
        }

    }
}

MovieApp/ViewComponents/CategoryMovieMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.ViewComponents
{
    public class CategoryMovieMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString() == "Index")
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryMovieRepository.CategoriesMovie);
        }
    }
}

MovieApp/ViewComponents/CategorySeriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.ViewComponents
{
    public class CategorySeriesMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString() == "Index")
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategorySeriesRepository.CategoriesSeries);
        }
    }
}

MovieApp/Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

MovieApp/Views/Home/Index.cshtml
<main role="main">
    <br />   <br />
    <section class="jumbotron text-center bg-gray">
        <div class="container">
            <h1 class="jumbotron-heading">Welcome to Movie App</h1>
            <br /><br />
            <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sapien lorem, sagittis nec vulputate posuere, venenatis at erat. Praesent euismod mi nec laoreet aliquam. Cras ultricies congue maximus. Proin ac nunc non lorem viverra tincidunt eu a ante. Suspendisse sit amet nisi laoreet, dictum elit eget, ultrices orci. </p>
            <p>
                <br />
                <a asp-action="Index" asp-controller="Movie" class="btn btn-primary my-2">Movies</a>
                <a asp-action="Index" asp-controller="Series" class="btn btn-primary my-2">Series</a>
            </p>
        </div>
    </section>
    <div class="album py-5 bg-white">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/1.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Movie" asp-route-id="1" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/Series4.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Series" asp-route-id="4" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/Series6.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Series" asp-route-id="6" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/Series1.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Series" asp-route-id="1" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/6.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Movie" asp-route-id="6" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/3.jpg" data-holder-rendered="true"> <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Movie" asp-route-id="3" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/Series2.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Series" asp-route-id="2" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/4.jpg" data-holder-rendered="true"> <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Movie" asp-route-id="4" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/2.jpg" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel felis non est iaculis bibendum vitae a massa. Ut dictum massa ut sapien accumsan finibus.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-action="Details" asp-controller="Movie" asp-route-id="2" class="btn btn-primary my-2">Details</a>
                                </div>
                                <small class="text-muted">- mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

MovieApp/Views/Home/List.cshtml
@model List<SearchModel>
@{
    ViewData["Title"] = "List";
}
<div class="album py-5 bg-white">
    <div class="container">
        <div class="row">
            <h3 style="text-align:center"><strong>Movies & TV Series:</strong></h3><br /><br /><br />
            <br /><br />
            @foreach (var items in Model)
            {
                @if (items.Status == 1)
                {
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/@items.ImageUrl" data-holder-rendered="true">
                            <div class="card-body">
                                <p><strong>@items.Name</strong></p>
                                <p class="card-text">@Html.Raw(@items.Description)</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a asp-action="Details" asp-controller="Movie" asp-route-id="@items.Id" class="btn btn-primary my-2">Details</a>
                                    </div>
                                    <small class="text-muted">- mins</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" alt="Thumbnail [100%x225]" style="height: 450px; width: 100%; display: block;" src="~/img/@items.ImageUrl" data-holder-rendered="true">
                            <div class="card-body">
                                <p><strong>@items.Name</strong></p>
                                <p class="card-text">@Html.Raw(@items.Description)</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a asp-action="Details" asp-controller="Series" asp-route-id="@items.Id" class="btn btn-primary my-2">Details</a>
                                    </div>
                                    <small class="text-muted">- mins</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

MovieApp/Views/Movie/Create.cshtml
<h1>Movie/Create</h1>

MovieApp/Views/Movie/Details.cshtml
@model Movie

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryMovieMenu")
        </div>
        <div class="col-md-9">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row no-gutter">
                        <div class="col-md-4">
                            <img src="~/img/@Model.ImageUrl" alt="@Model.ImageUrl" class="card-img" />
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title" style="text-align:center">
                                <p>@Model.Name</p>
                            </h5>
                            <p class="card-text">
                                @Html.Raw(@Model.Description)
                            </p>
                            <p class="card-text" style="text-align:end;">
                               <br /><br /><br /><br />

                                <small class="text-muted">- days ago</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

MovieApp/Views/Movie/Index.cshtml
@model IEnumerable<Movie>


<div class="row">
    <div class="col-md-3">
        @*<partial name="_menuMovies" model="Model.Categories" />*@
        @await Component.InvokeAsync("CategoryMovieMenu")
    </div>
    <div class="col-md-9">
        <partial name="_movies" model="Model" />
    </div>
</div>

MovieApp/Views/Movie/List.cshtml
<h1>Movie/List</h1>

MovieApp/Views/Movie/_movies.cshtml
@model IEnumerable<Movie>



@foreach (var movies in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/img/@movies.ImageUrl" alt="@movies.Name" class="card-img" />
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-little" style="text-align:center">
                        <a asp-action="Details" asp-controller="Movie" asp-route-id="@movies.Id">@movies.Name</a>
                    </h5>
                    <p class="card-text" style="text-align:center">
                        @Html.Raw(@movies.ShortDescription)
                    </p>
                    <br /><br /><br /><br />
                    <h6 class="card-little" style="text-align: match-parent;">
                        <strong>Director:</strong>@Html.Raw(@movies.Director)
                    </h6>
                    <h6 class="card-little">
                        <strong>Stars:</strong>@Html.Raw(@movies.Stars)
                    </h6>
                    <p class="card-text" style="text-align:end;">
                        <small class="text-muted">- days ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>

}

MovieApp/Views/Series/Details.cshtml
@model Series


    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategorySeriesMenu")
        </div>
        <div class="col-md-9">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row no-gutter">
                        <div class="col-md-4">
                            <img src="~/img/@Model.ImageUrl" alt="@Model.Description" class="card-img" />
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align:center">
                                    <p>@Model.Name</p>
                                </h5>
                                <p class="card-text">
                                    @Html.Raw(@Model.Description)
                                </p>
                                <p class="card-text" style="text-align:end;">
                                    <br /><br /><br />
                                    <small class="text-muted">- days ago</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

MovieApp/Views/Series/Index.cshtml
@model IEnumerable<Series>





<div class="row">
    <div class="col-md-3">
        @*<partial name="_menuMovies" model="Model.Categories" />*@
        @*@Html.Partial("_menuSeries",Model.Categories)*@
        @await Component.InvokeAsync("CategorySeriesMenu")
    </div>
    <div class="col-md-9">
        <partial name="_series" model="Model" />
    </div>
</div>

MovieApp/Views/Series/_series.cshtml
@model IEnumerable<Series>



@foreach (var series in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/img/@series.ImageUrl" alt="@series.Description" class="card-img" />
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title" style="text-align:center">
                        <a asp-action="Details" asp-controller="Series" asp-route-id="@series.Id">
                            @series.Name
                        </a>
                    </h5>
                    <p class="card-text">
                        @Html.Raw(@series.ShortDescription)
                    </p>
                    <br /><br /><br /><br />
                    <h6 class="card-little" style="text-align: match-parent;">
                        <strong>Director:</strong>@Html.Raw(series.Director)
                    </h6>
                    <h6 class="card-little">
                        <strong>Stars:</strong>@Html.Raw(series.Stars)
                    </h6>
                    <p class="card-text" style="text-align:end;">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
            </div>
        </div>

    </div>

}

MovieApp/Views/Shared/Components/CategoryMovieMenu/Default.cshtml
@model IEnumerable<CategoryMovie>

<div class="list-group">
    @foreach (var categories in Model)
    {
        <a asp-controller="Movie" asp-action="Index" asp-route-id="@categories.Id"
           class="list-group-item @(ViewBag.SelectedCategory==categories.Id.ToString()?"active":"")">
            @categories.Name
        </a>
    }
</div>




@*<product-list-pager
                        current-category="ViewBag.CurrentCategory"
                        current-page="ViewBag.CurrentPage"
                        page-count="ViewBag.PageCount"
                        page-size="ViewBag.PageSize">

    </product-list-pager>*@

MovieApp/Views/Shared/Components/CategorySeriesMenu/Default.cshtml
@model IEnumerable<CategorySeries>


<div class="list-group">
    @foreach (var categories in Model)
    {
        <a asp-controller="Series" asp-action="Index" asp-route-id="@categories.Id"
           class="list-group-item @(ViewBag.SelectedCategory==categories.Id.ToString()?"active":"")">
            @categories.Name
        </a>
    }
</div>

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Movie App</title>
    @await Html.PartialAsync("_LayoutCssPartial")
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <partial name="_navbar" />
    </header> 
    <main style="height:auto;">
        <div class="container mt-4">
            @RenderBody()
        </div>
    </main>
    <footer style="background-color:white; height:150px; padding-top:25px;">
        <partial name="_footer" />
    </footer>
</body>
</html>

MovieApp/Views/Shared/_navbar.cshtml
@{
    Layout = null;
}

<style>
    nav {
        width: 100%;
        height: 55px;
    }

        nav a {
            color: white !important;
            text-size-adjust: 150%;
            font-size: 20px;
        }

    .nav li {
        padding-right: 5px;
        font-size: 26px;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home"><strong>Movie App</strong></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Home" style="margin-left:20px;">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Movie">Movies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Series">Series</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul>
            <form class="navbar-nav" style="padding-right:35%;" method="get" asp-action="Search" asp-controller="Home">
                <div class="nav-item" id="idSearch">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" id="q">
                </div>
                <div class="nav-item" style="margin-left:2px;">
                    <button class="btn btn-outline-light my-2 my-sm-0" value="submit" type="submit">Search</button>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" style="margin-right:20px;">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>